package sbnz.integracija

import com.vet.mackolec.models.*

rule "DiseaseDetermination"
	salience (-((double) 100*$value / (double) $symptoms.size() + $value))
	// we are looking for disese that contains most of observed symptoms
	agenda-group "disease_determination"
    when 
    	$therapy: Therapy($observedSymptoms: observedSymptoms)
		$disease: Disease($symptoms: symptoms)
		
    	Number($value: intValue > 0) from accumulate(
        	$oS: ObservedSymptom(symptom memberOf $symptoms) from $observedSymptoms,
        	count($oS)
        )
        
    then
    	modify($therapy) { 
    		setDisease((Disease) $disease)
    	}
    	delete($disease);
end