package sbnz.integracija

import com.vet.mackolec.models.helper.*;
import com.vet.mackolec.models.*;
import com.vet.mackolec.models.enums.*;

import java.util.*;

global Double THRESHOLD; // hospitalization mean symptoms intensity treshold

function double calculateMeanIntensity(Set observedSymptoms) {
	double sumOfIntesity = 0.0;
	for (Object element: observedSymptoms)
	{ 
	    sumOfIntesity += ((ObservedSymptom) element).getLevel();
	}
	return sumOfIntesity / observedSymptoms.size();
}

rule "Initialize"
	agenda-group "hospitalization"
	salience 100
	when
	then
		kcontext.getKieRuntime().setGlobal("THRESHOLD", 3.7);
end 

rule "Hospitalization - based intensity of sypmtoms -- NEED"
	agenda-group "hospitalization"
    when 
    	$therapy: Therapy($observedSymptoms: observedSymptoms, hospitalization == Hospitalization.UNDEFINED)
    	eval(calculateMeanIntensity($therapy.getObservedSymptoms()) > THRESHOLD)
    then 
    	$therapy.setHospitalization(Hospitalization.NEED);
end


rule "Hospitalization - based intensity of sypmtoms -- NO_NEED"
	agenda-group "hospitalization"
    when 
    	$therapy: Therapy($observedSymptoms: observedSymptoms, hospitalization == Hospitalization.UNDEFINED)
    	eval(calculateMeanIntensity($therapy.getObservedSymptoms()) <= THRESHOLD)
    then 
    	$therapy.setHospitalization(Hospitalization.NO_NEED);
end

