package com.sample

import com.vet.mackolec.models.*;
import com.vet.mackolec.models.enums.*;


import java.util.*;

query "Cats that have acquired immunity to the drug they used" (Long $tresholdDate)
	
	Cat($jmbm: jmbm)
	Medicine($id: id)

	$therapies: List(size > 0) from collect (
		Therapy(
			cat.jmbm == $jmbm, 
			medicine.id == $id, 
			date >= $tresholdDate
		)
    )
    
    Number(intValue >= 4) from accumulate (
        $t: Therapy() from $therapies,
        count($t)
    )  
end

query "Cats at risk of organ damage - SREDNJE_JAK_LEK" (Long $tresholdDate)
	Cat($jmbm: jmbm)
	Medicine($id: id)

	$therapies: List(size > 0) from collect (
		Therapy(
			cat.jmbm == $jmbm, 
			medicine.id == $id,
			medicine.getCategory() == MedicineCategory.SREDNJE_JAK_LEK,
			therapyStrength.getValue() >= TherapyStrength.MG400.getValue(),
			date >= $tresholdDate
		)
    )
    
    Number(intValue >= 6) from accumulate (
        $t: Therapy() from $therapies,
        count($t)
    )
end

query "Cats at risk of organ damage - JAK_LEK" (Long $tresholdDate)
	Cat($jmbm: jmbm)
	Medicine($id: id)

	$therapies: List(size > 0) from collect (
		Therapy(
			cat.jmbm == $jmbm, 
			medicine.id == $id,
			medicine.getCategory() == MedicineCategory.JAK_LEK, 
			therapyStrength.getValue() >= TherapyStrength.MG300.getValue(),
			date >= $tresholdDate
		)
    )
    
    Number(intValue >= 6) from accumulate (
        $t: Therapy() from $therapies,
        count($t)
    )
end

/*
query "Cats with possible chronic diseases" (Long $tresholdDate)
	Cat($jmbm: jmbm)
	Disease($id: id)

	$therapies: List(size > 0) from collect (
		Therapy(
			cat.jmbm == $jmbm, 
			disease.id == $id,
			disease.name != "Dijabetes",
			date >= $tresholdDate
		)
    )
    
    Number(intValue >= 4) from accumulate (
        $t: Therapy() from $therapies,
        count($t)
    )
end

query "Cat breed average occurance in all therapies" (String $catBreed)

	$therapies: List(size > 0) from collect (
		Therapy()
    )
    
    Number($value: intValue > 0) from accumulate (
        Therapy($t:this, cat.breed.name() == $catBreed) from $therapies,
        count($t)
    )
end
*/