package sbnz.integracija

import com.vet.mackolec.models.Therapy;
import com.vet.mackolec.models.enums.TherapyStrength;
import com.vet.mackolec.models.enums.MedicineCategory;

rule "TherapyDetermination MG100"
	agenda-group "therapy_determination"
    when 
    	$therapy: Therapy(therapyStrength == TherapyStrength.UNDEFINED, $medicine : medicine, $cat : cat)
    	eval($medicine.getCategory() == MedicineCategory.JAK_LEK)
    	eval($cat.getWeight() < 500)
    then 
    	$therapy.setTherapyStrength(TherapyStrength.MG100);
end

rule "TherapyDetermination MG200 - SLAB_LEK"
	agenda-group "therapy_determination"
    when 
    	$therapy: Therapy(therapyStrength == TherapyStrength.UNDEFINED, $medicine : medicine, $cat : cat)
    	eval($medicine.getCategory() == MedicineCategory.SLAB_LEK)
    	eval($cat.getWeight() < 500)
    then 
    	$therapy.setTherapyStrength(TherapyStrength.MG200);
end

rule "TherapyDetermination MG200 - SREDNJE_JAK_LEK"
	agenda-group "therapy_determination"
    when 
    	$therapy: Therapy(therapyStrength == TherapyStrength.UNDEFINED, $medicine : medicine, $cat : cat)
    	eval($medicine.getCategory() == MedicineCategory.SREDNJE_JAK_LEK)
    	eval($cat.getWeight() < 1200)	
    then 
    	$therapy.setTherapyStrength(TherapyStrength.MG200);
end


rule "TherapyDetermination MG200 - JAK_LEK"
	agenda-group "therapy_determination"
    when 
    	$therapy: Therapy(therapyStrength == TherapyStrength.UNDEFINED, $medicine : medicine, $cat : cat)
    	eval($medicine.getCategory() == MedicineCategory.JAK_LEK) 
    	eval($cat.getWeight() >= 500 && $cat.getWeight() < 3000)
    then 
    	$therapy.setTherapyStrength(TherapyStrength.MG200);
end


rule "TherapyDetermination MG300 - SLAB_LEK"
	agenda-group "therapy_determination"
    when 
    	$therapy: Therapy(therapyStrength == TherapyStrength.UNDEFINED, $medicine : medicine, $cat : cat)
    	eval($medicine.getCategory() == MedicineCategory.SLAB_LEK)
    	eval($cat.getWeight() >= 500 && $cat.getWeight() < 1200)
    then
    	$therapy.setTherapyStrength(TherapyStrength.MG300);
end


rule "TherapyDetermination MG300 - SREDNJE_JAK_LEK"
	agenda-group "therapy_determination"
    when 
    	$therapy: Therapy(therapyStrength == TherapyStrength.UNDEFINED, $medicine : medicine, $cat : cat)
    	eval($medicine.getCategory() == MedicineCategory.SREDNJE_JAK_LEK)
    	eval($cat.getWeight() >= 1200 && $cat.getWeight() < 3000)
    then 
    	$therapy.setTherapyStrength(TherapyStrength.MG300);
end


rule "TherapyDetermination MG300 - JAK_LEK"
	agenda-group "therapy_determination"
    when 
    	$therapy: Therapy(therapyStrength == TherapyStrength.UNDEFINED, $medicine : medicine, $cat : cat)
    	eval($medicine.getCategory() == MedicineCategory.JAK_LEK)
    	eval($cat.getWeight() >= 3000 && $cat.getWeight() < 7000)
    then 
    	$therapy.setTherapyStrength(TherapyStrength.MG300);
end


rule "TherapyDetermination MG400 - SLAK_LEK"
	agenda-group "therapy_determination"
    when 
    	$therapy: Therapy(therapyStrength == TherapyStrength.UNDEFINED, $medicine : medicine, $cat : cat)
    	eval($medicine.getCategory() == MedicineCategory.SLAB_LEK)
    	eval($cat.getWeight() >= 1200 && $cat.getWeight() < 3000)
    then 
    	$therapy.setTherapyStrength(TherapyStrength.MG400);
end


rule "TherapyDetermination MG400 - SREDNJE_JAK_LEK"
	agenda-group "therapy_determination"
    when 
    	$therapy: Therapy(therapyStrength == TherapyStrength.UNDEFINED, $medicine : medicine, $cat : cat)
    	eval($medicine.getCategory() == MedicineCategory.SREDNJE_JAK_LEK)
    	eval($cat.getWeight() >= 3000 && $cat.getWeight() < 7000)
    then 
    	$therapy.setTherapyStrength(TherapyStrength.MG400);
end


rule "TherapyDetermination MG400 - JAK_LEK"
	agenda-group "therapy_determination"
    when 
    	$therapy: Therapy(therapyStrength == TherapyStrength.UNDEFINED, $medicine : medicine, $cat : cat)
    	eval($medicine.getCategory() == MedicineCategory.JAK_LEK)
    	eval($cat.getWeight() >= 7000)
    then 
    	$therapy.setTherapyStrength(TherapyStrength.MG400);
end


rule "TherapyDetermination MG500 - SLAB_LEK"
	agenda-group "therapy_determination"
    when 
    	$therapy: Therapy(therapyStrength == TherapyStrength.UNDEFINED, $medicine : medicine, $cat : cat)
    	eval($medicine.getCategory() == MedicineCategory.SLAB_LEK)
    	eval($cat.getWeight() >= 3000)
    then 
    	$therapy.setTherapyStrength(TherapyStrength.MG500);
end


rule "TherapyDetermination MG500 - SREDNJE_JAK_LEK"
	agenda-group "therapy_determination"
    when 
    	$therapy: Therapy(therapyStrength == TherapyStrength.UNDEFINED, $medicine : medicine, $cat : cat)
    	eval($medicine.getCategory() == MedicineCategory.SREDNJE_JAK_LEK)
    	eval($cat.getWeight() >= 7000)
    then 
    	$therapy.setTherapyStrength(TherapyStrength.MG500);
end